<Project Sdk="Microsoft.NET.Sdk">
  <Import Condition="EXISTS('Mapbox.Maui.props')"
          Project="Mapbox.Maui.props" />
  <Import Condition="EXISTS('Mapbox.Maui.targets')"
          Project="Mapbox.Maui.targets" />
  <Target Name="_CleanAarOutputPath"
          AfterTargets="_CreateAar"
          BeforeTargets="_IncludeAarInNuGetPackage">
    <Delete Files="$(_AarOutputPath)" />
  </Target>

  <PropertyGroup>
    <TargetFrameworks>net10.0;net10.0-android;net10.0-ios;</TargetFrameworks>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>

    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.4</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">27.0</SupportedOSPlatformVersion>
    <RootNamespace>MapboxMaui</RootNamespace>
    <SkipValidateMauiImplicitPackageReferences>true</SkipValidateMauiImplicitPackageReferences>
  </PropertyGroup>

  <PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
  </PropertyGroup>

  <!-- Android -->
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <WarningLevel>4</WarningLevel>
    <LangVersion>latestmajor</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <LangVersion>latestmajor</LangVersion>
  </PropertyGroup>
  <ItemGroup Condition=" $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'android' ">
    <Compile Remove="**\**\*.Android.cs" />
  </ItemGroup>

  <!-- Both iOS and Mac Catalyst -->
  <ItemGroup Condition=" $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'ios' AND $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'maccatalyst' ">
    <Compile Remove="**\**\*.MaciOS.cs" />
    <None Include="**\**\*.MaciOS.cs"
          Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
  </ItemGroup>

  <!-- iOS -->
  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'ios'">
    <Compile Remove="**\**\*.iOS.cs" />
  </ItemGroup>

  <PropertyGroup>
    <AndroidTargetSdkVersion>36</AndroidTargetSdkVersion>
    <!--<AndroidSdkDirectory Condition=" '$(OS)' == 'Unix' ">$(Home)/Library/Android/sdk</AndroidSdkDirectory>
    <AndroidSdkDirectory Condition=" '$(OS)' != 'Unix' ">$(UserProfile)/AppData/Local/Android/sdk</AndroidSdkDirectory>-->
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Mapbox.Maui</PackageId>
    <Title>Mapbox SDK for .NET MAUI</Title>
    <Summary>.NET MAUI control and APIs for Mapbox</Summary>
    <Description>.NET MAUI control and APIs for Mapbox</Description>
    <Authors>tuyen,tuyen-vuduc</Authors>
    <Owners>tuyen,tuyen-vuduc</Owners>
    <Copyright>© tuyen-vuduc. All rights reserved.</Copyright>
    <RepositoryUrl>https://github.com/tuyen-vuduc/mapbox-maui</RepositoryUrl>
    <PackageProjectUrl>https://mapbox.tuyen-vuduc.tech</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageVersion>11.15.2-ndk27</PackageVersion>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>tv-mapbox.png</PackageIcon>
  </PropertyGroup>
  <PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
    <CreatePackage>false</CreatePackage>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../../assets/tv-mapbox.png"
          Pack="True"
          PackagePath="tv-mapbox.png" />
    <None Include="../../../LICENSE"
          Pack="True"
          PackagePath="" />
    <None Include="../../../README.md"
          Pack="True"
          PackagePath="README.md" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug"
                      Version="10.0.0" />
    <PackageReference Include="Xamarin.Build.Download"
                      Version="0.11.4" />
    <PackageReference Include="GeoJSON.Text"
                      Version="1.1.0" />
    <PackageReference Include="Microsoft.Maui.Controls"
                      Version="$(MauiVersion)" />
    <PackageReference Update="Microsoft.Maui.Controls.Compatibility"
                       Version="$(MauiVersion)" />
  </ItemGroup>
  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
    <PackageReference Include="MapboxMapsObjC.iOS"
                      Version="11.8.0" />
    <PackageReference Include="MapboxMaps.iOS"
                      Version="11.8.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Models\Gestures\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Platforms\iOS\TemplateHelpers.cs">
      <ExcludeFromCurrentConfiguration>false</ExcludeFromCurrentConfiguration>
    </Compile>
    <Compile Update="Platforms\iOS\ViewAnnotations\MapboxViewHandler.ViewAnnotations.cs">
      <ExcludeFromCurrentConfiguration>false</ExcludeFromCurrentConfiguration>
    </Compile>
    <Compile Update="Platforms\iOS\ViewAnnotations\ViewAnnotationOptionsExtensions.cs">
      <ExcludeFromCurrentConfiguration>false</ExcludeFromCurrentConfiguration>
    </Compile>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
    <PackageReference Include="Com.Mapbox.Maps.AndroidNdk27" Version="11.15.2" />
  </ItemGroup>
  <ProjectExtensions>
    <MonoDevelop>
      <Properties>
        <Policies>
          <DotNetNamingPolicy DirectoryNamespaceAssociation="None"
                              ResourceNamePolicy="FileFormatDefault" />
        </Policies>
      </Properties>
    </MonoDevelop>
  </ProjectExtensions>
  <!--<Target Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'"
          Name="_GradleDependencyResolverTrigger"
          DependsOnTargets="_GradleSync"
          BeforeTargets="_BuildLibraryImportsCache" />-->
</Project>
